### ISSUE TITLE
ci restarting

### ISSUE THREAD

**Issue by cseed** [hail-is/ci#94]
@danking I might need help with this.  The ci container is crashing:

```
hail-ci-deployment-7797745cb9-8srxs   0/1       CrashLoopBackOff   17         5d
```

17 is the number of restarts.  I grabbed the logs (with and without -p, the results were same since the pod was restart) and the log doesn't contain an error.  I put it at gs://hail-cseed/ci-deploy-logs in case that helps.

It looks like this might be caused by my recent batch update but I don't see why.

**Comment by cseed** [comment]
Ah, health check is failing.  It looks like it might be timing out waiting for batch.

```
  Type     Reason      Age                 From                                             Message
  ----     ------      ----                ----                                             -------
  Warning  Unhealthy   8m (x4916 over 5d)  kubelet, gke-cs-test-default-pool-ef886a34-crx1  Liveness probe failed: Get http://10.56.112.128:5000/healthcheck: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  FailedSync  3m (x153 over 1h)   kubelet, gke-cs-test-default-pool-ef886a34-crx1  Error syncing pod
```

I'm seeing (batch internal) timeouts in the batch logs:

```
ERROR:batch:run_forever: target kube_event_loop threw exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/batch/server.py", line 335, in run_forever
    target(*args, **kwargs)
  File "/batch/server.py", line 359, in kube_event_loop
    requests.post('http://127.0.0.1:5000/pod_changed', json={'pod_name': name}, timeout=120)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=120)
```

Maybe `refresh_k8s_state` is taking too long?  I'm going to update with additional logging with timing.

**Comment by cseed** [comment]
k8s latency doesn't seem to be the problem:

```
INFO	| 2018-09-12 21:28:03,917 	| server.py 	| refresh_k8s_state:324 | started k8s state refresh
INFO	| 2018-09-12 21:28:03,956 	| server.py 	| refresh_k8s_state:343 | k8s state refresh complete
INFO	| 2018-09-12 21:28:03,957 	| _internal.py 	| _log:88 | 127.0.0.1 - - [12/Sep/2018 21:28:03] "POST /refresh_k8s_state HTTP/1.1" 204 -
```

At least early on.  It might get worse when the number of pods increases.  I'll keep an eye on it.

**Comment by danking** [comment]
This was caused by batch making a synchronous call to CI when a job finished and CI, in that response, making a synchronous call to batch to delete the job. We resolved this by making the batch calls asynchronous (I think?)
